### ISSUE TITLE
Change domains in idp-metadata.xml

### ISSUE THREAD

**Issue by irfanhakim-as** [sifulan-access-federation/ifirexman-shibboleth-idp#1]
`idp-metadata.xml` is currently filled with instances of `idp.vikings.e-id.my` that should be made generic for user's modification

**Comment by irfanhakim-as** [comment]
More things to change:

`idp-metadata.xml`
- `vikings.e-id.my`
- `https://sifulan.my`
- `mailto:support@sifulan.my`

`messages.properties`
- `support@sifulan.my`

`idp.properties`
- `syslog.sifulan.my`

`attribute-resolver.xml`
- `urn:mace:terena.org:schac:homeOrganizationType:my:other`

**Comment by farhansj** [comment]
Now user can customized their IdP in the values.yaml file. The rest will be taken care of by Helm template
